export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'LOGOUT'
export const AUTH_CHECKING = 'AUTH_CHECKING'
export const AUTH_ACCOUNT = 'AUTH_ACCOUNT'